# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

jobs:
  build-and-test:
    name: Build and test with maven
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build and test with Maven
      run: mvn -B package --file pom.xml

  docker-build:
    needs: build-and-test
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
      run: docker build -t quiz-app . --file Dockerfile --tag service:${{ github.sha }}
      with:
        tags: ${{ github.sha }}, latest

  docker-upload:
    name: Docker Upload
    runs-on: ubuntu-latest
    steps:
      run:
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  trivy-setup:
    needs: [docker-build]
    name: Manual Trivy Setup
    uses: aquasecurity/setup-trivy@v0.2.0
    with:
      cache: true
      version: v0.69.1

  trivy-repo-scan:
    needs: trivy-setup
    name: Run Trivy vulnerability scanner in repo mode
    uses: aquasecurity/trivy-action@master
    with:
      scan-type: 'fs'
      ignore-unfixed: true
      format: 'sarif'
      output: 'trivy-results.sarif'
      severity: 'CRITICAL'
      skip-setup-trivy: true

  trivy-image-scan:
    needs: trivy-setup
    name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@0.33.1
    with:
      image-ref: 'quiz-app:${{ github.sha }}'
      format: 'table'
      exit-code: '1'
      ignore-unfixed: true
      vuln-type: 'os,library'
      severity: 'CRITICAL,HIGH'
      skip-setup-trivy: true

# Run build and package on every push on every branch apart from main
on:
  push:
    branches:
      - '*'
      - '!main'
    uses: build-and-test

  pull_request:
    branches: [ "feature/*","bugfix/*","develop","main" ]
    uses: docker-build
